### ISSUE TITLE
panic: unaligned 64-bit atomic operation (on Raspberry Pi4 32 bit)

### ISSUE THREAD

**Issue by jha749** [zinclabs/zincsearch#511]
I'm trying out Zinc/Fluent-bit combination on my Raspberry Pi 4B, running a 32-bit version of Raspbian.

I used the official, latest 0.3.1 Zinc docker image from here: https://gallery.ecr.aws/zinclabs/zinc (the ARM v7 version). It starts just fine first time, I can access the UI, play around with it, etc. It's in debug mode. When I send the first data through Fluent Bit, it crashes: 

````
{"level":"info","method":"POST","code":200,"took":22,"time":"2022-09-05T16:06:49Z","message":"/api/_bulk"}
panic: unaligned 64-bit atomic operation

goroutine 68 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x7a982b4, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:291 +0x14
github.com/zinclabs/zinc/pkg/core.(*Index).UpdateMetadataByShard(0x60366f0, {0x629cb60, 0xb})
        /go/src/github.com/zinclabs/zinc/pkg/core/index.go:292 +0x278
github.com/zinclabs/zinc/pkg/core.(*IndexShard).ConsumeWAL(0x617e680)
        /go/src/github.com/zinclabs/zinc/pkg/core/index_shards_wal.go:236 +0xf10
github.com/zinclabs/zinc/pkg/core.(*IndexShardWALList).ConsumeWAL.func1()
        /go/src/github.com/zinclabs/zinc/pkg/core/index_shards_wallist.go:91 +0x54
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa8
````

Also subsequent start attempts won't work and crash:
````
{"level":"debug","time":"2022-09-05T16:25:23Z","message":"open .env: no such file or directory"}
{"level":"info","time":"2022-09-05T16:25:23Z","message":"Loading  index... [logstash-2022.09.05:disk] shards[3:3]"}
{"level":"info","time":"2022-09-05T16:25:23Z","message":"Starting Zinc 0.3.1"}
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x6ae08dc)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/zinclabs/zinc/pkg/core.(*telemetry).GetIndexSize(0x68a2e60, {0x69b8e09, 0x13})
        /go/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:157 +0x50
github.com/zinclabs/zinc/pkg/core.(*telemetry).TotalIndexSize(0x68a2e60)
        /go/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:150 +0x6c
github.com/zinclabs/zinc/pkg/core.(*telemetry).Instance(0x68a2e60)
        /go/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:109 +0xd0
main.telemetry()
        /go/src/github.com/zinclabs/zinc/cmd/zinc/main.go:118 +0x20
main.main()
        /go/src/github.com/zinclabs/zinc/cmd/zinc/main.go:64 +0x180
````

When I clear the data directory, it will start again, but as soon as I send some data through Fluent Bit it crashes again.

It seems to be a problem with the atomic package, searching on the internet I found several hits, e.g.:
https://github.com/elastic/beats/issues/3273
https://github.com/golang/go/issues/23345

Unfortunately I don't understand Golang well enough to go about debugging it myself, but any fixes or pointers to fix would be appreciated, happy to test any fix on my RPi.

**Comment by hengfeiyang** [comment]
@jha749 can you help me do some test? you can find me in Slack, let's do some test on your device, we have no 32bit device.

**Comment by tedaimengdetudi** [comment]
Oh,I met the problem like you.Have you solved it?

**Comment by hengfeiyang** [comment]
@tedaimengdetudi Can you build zinc with the main branch to have a try? because we didn't build the arm32 version.

**Comment by Alward-Sensai** [comment]
Same issue here, but with debian 64 on Raspberry 4. Issue apears after creating and putting data into an index, if you delete it, restarts fine and stays stable. Once you create and fill an index, in a while it dies with the error. I have two docker instances over arm and intel debian linux with  no issues. Seems specific to ARM with the official docker image.

**Comment by martinl** [comment]
I tested the latest arm7 release version (0.3.6) following the syslog-ng guide. zinc crashed and fails to start with similar error message:

```
{"level":"debug","time":"2023-02-09T11:13:32+02:00","message":"open .env: no such file or directory"}
{"level":"info","time":"2023-02-09T11:13:32+02:00","message":"Loading  index... [syslog-ng:disk] shards[3:3]"}
{"level":"info","time":"2023-02-09T11:13:32+02:00","message":"Starting Zinc 0.3.6"}
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	/root/.goenv/versions/1.18.8/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x5aee87c)
	/root/.goenv/versions/1.18.8/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/zinclabs/zinc/pkg/core.(*telemetry).GetIndexSize(0x58946e0, {0x72e0017, 0x9})
	/codebuild/output/src901491802/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:157 +0x50
github.com/zinclabs/zinc/pkg/core.(*telemetry).TotalIndexSize(0x58946e0)
	/codebuild/output/src901491802/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:150 +0x6c
github.com/zinclabs/zinc/pkg/core.(*telemetry).Instance(0x58946e0)
	/codebuild/output/src901491802/src/github.com/zinclabs/zinc/pkg/core/telemetry.go:109 +0xd0
main.telemetry()
	/codebuild/output/src901491802/src/github.com/zinclabs/zinc/cmd/zinc/main.go:118 +0x20
main.main()
	/codebuild/output/src901491802/src/github.com/zinclabs/zinc/cmd/zinc/main.go:64 +0x180
```
